### ISSUE TITLE
.

### ISSUE THREAD

**Issue by redkerry135** [UwUham/subg-shitposts#7]
hi

**Comment by suburbGira** [comment]
no

**Comment by redkerry135** [comment]
sorry

**Comment by UwUham** [comment]
ok but what if yes

**Comment by redkerry135** [comment]
:scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat::scream_cat:

**Comment by suburbGira** [comment]
in that case, perhaps
